# Generated by Django 3.2.13 on 2023-07-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('Version', models.CharField(max_length=11)),
                ('Heading', models.CharField(max_length=100)),
                ('ShortDescription', models.TextField(max_length=300)),
                ('MeanDescription', models.TextField(max_length=500)),
                ('LongDescription', models.TextField(max_length=1000)),
                ('UserName1', models.CharField(max_length=100)),
                ('UserName2', models.CharField(max_length=100, null=True)),
                ('UserName3', models.CharField(max_length=100, null=True)),
                ('UserExp1', models.CharField(max_length=255)),
                ('UserExp2', models.CharField(max_length=255, null=True)),
                ('UserExp3', models.CharField(max_length=255, null=True)),
                ('ExtraTextField1', models.TextField(max_length=500, null=True)),
                ('ExtraTextField2', models.TextField(max_length=500, null=True)),
                ('ExtraTextField3', models.TextField(max_length=500, null=True)),
                ('Link1', models.CharField(max_length=255, null=True)),
                ('Link2', models.CharField(max_length=255, null=True)),
                ('Link3', models.CharField(max_length=255, null=True)),
                ('PriceRating', models.FloatField()),
                ('GraphicsRating', models.FloatField()),
                ('LevelsRating', models.FloatField()),
                ('DifficultyRating', models.FloatField()),
                ('Rating', models.FloatField()),
                ('ExtraIntField1', models.IntegerField()),
                ('ExtraIntField2', models.IntegerField()),
                ('ExtraIntField3', models.IntegerField()),
                ('IsGameAvailable', models.BooleanField()),
                ('DownloadButtonState', models.BooleanField()),
                ('ExtraBoolField1', models.BooleanField()),
                ('ExtraBoolField2', models.BooleanField()),
                ('ExtraBoolField3', models.BooleanField()),
                ('Image1', models.FileField(max_length=255, upload_to='media/Images/')),
                ('Image2', models.FileField(max_length=255, upload_to='media/Images/')),
                ('Image3', models.FileField(max_length=255, upload_to='media/Images/')),
                ('Image4', models.FileField(max_length=255, upload_to='media/Images')),
                ('Image5', models.FileField(default=None, max_length=255, null=True, upload_to='media/Images')),
                ('Image6', models.FileField(default=None, max_length=255, null=True, upload_to='media/Images')),
                ('Image7', models.FileField(default=None, max_length=255, null=True, upload_to='media/Images')),
                ('Video1', models.FileField(default=None, max_length=255, null=True, upload_to='media/Videos')),
                ('Video2', models.FileField(default=None, max_length=255, null=True, upload_to='media/Videos')),
                ('GameFile', models.FileField(default=None, max_length=255, null=True, upload_to='media/Games')),
                ('Dependencies', models.FileField(default=None, max_length=255, null=True, upload_to='media/Games')),
                ('GameName', models.SlugField(default='')),
            ],
        ),
    ]
