# Generated by Django 3.2.13 on 2023-07-23 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FCGStore', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Games',
            new_name='Game',
        ),
    ]
